### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by hermanschmit** [sinkuu/edif-rs#1]
Would you consider including a license file for this project, preferably MIT.

I'd like to use this, possibly professionally, and possibly extend it, but I can't without the license being specified.

**Comment by sinkuu** [comment]
Sorry for the late reply! I added license files. https://github.com/sinkuu/edif-rs/commit/081ddab82db787e1e7ce0e026186ccd6e2542fae
I chose "MIT or Apache-2.0", which is a common license in Rust ecosystem, and you can use this project under MIT license it that fits you.
